const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({viewport:{width:1280,height:720}});
  const errs=[];
  page.on('pageerror',e=>errs.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
  await page.goto('http://127.0.0.1:5174/world/ar/invite.html',{waitUntil:'domcontentloaded',timeout:30000});
  await page.waitForTimeout(2000);
  const initMode = await page.evaluate(()=>document.body.dataset.arMode);
  console.log('初始模式:', initMode);
  await page.click('#demo2');
  await page.waitForTimeout(1200);
  const mode = await page.evaluate(()=>document.body.dataset.arMode);
  const phase = await page.evaluate(()=>document.body.dataset.phase);
  console.log('demo后:', mode, '| 阶段:', phase);
  await page.waitForTimeout(3500);
  const finalPhase = await page.evaluate(()=>document.body.dataset.phase);
  const enterShown = await page.evaluate(()=>{const b=document.getElementById('enter-btn-ar');return b&&b.classList.contains('show');});
  console.log('最终阶段:', finalPhase, '| 进入按钮:', enterShown);
  await page.screenshot({path:'zeen-tools/invite-demo.png'});
  const realErrs=errs.filter(e=>!/GPU stall|favicon|Could not load/i.test(e));
  console.log('errors:', realErrs.length);
  realErrs.slice(0,3).forEach(e=>console.log('  '+e));
  await browser.close();
  let pass = mode==='mouse' && finalPhase==='hold' && enterShown && realErrs.length===0;
  console.log(pass?'\n=== INVITE PASSED ===':'\n=== INVITE CHECK ===');
  process.exit(pass?0:1);
})();
