const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({viewport:{width:1280,height:720}});
  const errs=[];
  page.on('pageerror',e=>errs.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
  await page.goto('http://127.0.0.1:5176/world/ar/tryon.html',{waitUntil:'domcontentloaded',timeout:20000});
  await page.waitForTimeout(1500);
  const initProp = await page.evaluate(()=>document.body.dataset.currentProp);
  const selBtns = await page.evaluate(()=>document.querySelectorAll('#prop-selector .prop-btn').length);
  console.log('初始款式:', initProp, '| 配饰按钮数:', selBtns);
  await page.click('#demo2');
  await page.waitForTimeout(1500);
  const mode = await page.evaluate(()=>document.body.dataset.arMode);
  console.log('演示模式:', mode);
  await page.keyboard.press('3');
  await page.waitForTimeout(300);
  const afterKey = await page.evaluate(()=>document.body.dataset.currentProp);
  console.log('按键3后:', afterKey);
  await page.screenshot({path:'zeen-tools/tryon-demo.png'});
  const realErrs=errs.filter(e=>!/GPU stall|favicon|Could not load/i.test(e));
  console.log('errors:', realErrs.length);
  realErrs.slice(0,3).forEach(e=>console.log('  '+e));
  await browser.close();
  let pass = initProp==='圆框眼镜' && selBtns===12 && mode==='mouse' && realErrs.length===0;
  console.log(pass?'\n=== TRYON PASSED ===':'\n=== TRYON CHECK ===');
  process.exit(pass?0:1);
})();
